# Travis configuration file, for testing the development environment.
# Minimal tests are written here - contributions should pass CI before being reviewed
language: python
python:
- '2.7'
- pypy
before_install:
# Set up OS-level dependencies, if necessary

install:
  - pip install jupyter_client
script:
# run tests
after_script:
# post-processing, uploads, etc
notifications:
# who wants the good news !?
